// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-rc.1
// 	protoc        (unknown)
// source: dnsproxy/dns.proto

package dnsproxy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Wan being set to true will cause WAN addresses to be sent in the response
	// instead of the LAN addresses which are the default
	Message []byte `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *ResolveRequest) Reset() {
	*x = ResolveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dnsproxy_dns_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest) ProtoMessage() {}

func (x *ResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dnsproxy_dns_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return file_dnsproxy_dns_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type ResolveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message []byte `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *ResolveResponse) Reset() {
	*x = ResolveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dnsproxy_dns_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse) ProtoMessage() {}

func (x *ResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dnsproxy_dns_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse.ProtoReflect.Descriptor instead.
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return file_dnsproxy_dns_proto_rawDescGZIP(), []int{1}
}

func (x *ResolveResponse) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_dnsproxy_dns_proto protoreflect.FileDescriptor

var file_dnsproxy_dns_proto_rawDesc = []byte{
	0x0a, 0x12, 0x64, 0x6e, 0x73, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x64, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6d, 0x6b, 0x65, 0x65, 0x6c, 0x65, 0x72, 0x2e, 0x64, 0x6e,
	0x73, 0x22, 0x2a, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2b, 0x0a,
	0x0f, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x4d, 0x0a, 0x03, 0x44, 0x6e,
	0x73, 0x12, 0x46, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x12, 0x1b, 0x2e, 0x6d,
	0x6b, 0x65, 0x65, 0x6c, 0x65, 0x72, 0x2e, 0x64, 0x6e, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x6c,
	0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6d, 0x6b, 0x65, 0x65,
	0x6c, 0x65, 0x72, 0x2e, 0x64, 0x6e, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x8f, 0x01, 0x0a, 0x0f, 0x63, 0x6f,
	0x6d, 0x2e, 0x6d, 0x6b, 0x65, 0x65, 0x6c, 0x65, 0x72, 0x2e, 0x64, 0x6e, 0x73, 0x42, 0x08, 0x44,
	0x6e, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x6b, 0x65, 0x65, 0x6c, 0x65, 0x72, 0x2f, 0x64, 0x6e,
	0x73, 0x2d, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x64, 0x6e, 0x73, 0x70, 0x72, 0x6f, 0x78, 0x79,
	0xa2, 0x02, 0x03, 0x4d, 0x44, 0x58, 0xaa, 0x02, 0x0b, 0x4d, 0x6b, 0x65, 0x65, 0x6c, 0x65, 0x72,
	0x2e, 0x44, 0x6e, 0x73, 0xca, 0x02, 0x0b, 0x4d, 0x6b, 0x65, 0x65, 0x6c, 0x65, 0x72, 0x5c, 0x44,
	0x6e, 0x73, 0xe2, 0x02, 0x17, 0x4d, 0x6b, 0x65, 0x65, 0x6c, 0x65, 0x72, 0x5c, 0x44, 0x6e, 0x73,
	0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0c, 0x4d,
	0x6b, 0x65, 0x65, 0x6c, 0x65, 0x72, 0x3a, 0x3a, 0x44, 0x6e, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_dnsproxy_dns_proto_rawDescOnce sync.Once
	file_dnsproxy_dns_proto_rawDescData = file_dnsproxy_dns_proto_rawDesc
)

func file_dnsproxy_dns_proto_rawDescGZIP() []byte {
	file_dnsproxy_dns_proto_rawDescOnce.Do(func() {
		file_dnsproxy_dns_proto_rawDescData = protoimpl.X.CompressGZIP(file_dnsproxy_dns_proto_rawDescData)
	})
	return file_dnsproxy_dns_proto_rawDescData
}

var file_dnsproxy_dns_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dnsproxy_dns_proto_goTypes = []interface{}{
	(*ResolveRequest)(nil),  // 0: mkeeler.dns.ResolveRequest
	(*ResolveResponse)(nil), // 1: mkeeler.dns.ResolveResponse
}
var file_dnsproxy_dns_proto_depIdxs = []int32{
	0, // 0: mkeeler.dns.Dns.Resolve:input_type -> mkeeler.dns.ResolveRequest
	1, // 1: mkeeler.dns.Dns.Resolve:output_type -> mkeeler.dns.ResolveResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dnsproxy_dns_proto_init() }
func file_dnsproxy_dns_proto_init() {
	if File_dnsproxy_dns_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dnsproxy_dns_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dnsproxy_dns_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dnsproxy_dns_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dnsproxy_dns_proto_goTypes,
		DependencyIndexes: file_dnsproxy_dns_proto_depIdxs,
		MessageInfos:      file_dnsproxy_dns_proto_msgTypes,
	}.Build()
	File_dnsproxy_dns_proto = out.File
	file_dnsproxy_dns_proto_rawDesc = nil
	file_dnsproxy_dns_proto_goTypes = nil
	file_dnsproxy_dns_proto_depIdxs = nil
}
